### ISSUE TITLE
`RecusionError` when trying to Load Settings

### ISSUE THREAD

**Issue by olivierov** [OneKiwiTech/kicad-length-matching#5]
# System
## KiCad
```
Application: KiCad PCB Editor (64-bit)

Version: (6.0.7), release build

Libraries:
	wxWidgets 3.1.7
	libcurl/7.83.1-DEV Schannel zlib/1.2.12

Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jul 26 2022 02:49:38
	wxWidgets: 3.1.7 (wchar_t,wx containers)
	Boost: 1.79.0
	OCC: 7.6.0
	Curl: 7.83.1-DEV
	ngspice: 37
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON
```
## Hardware
```
Device name	-
Processor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
Installed RAM	64.0 GB (63.9 GB usable)
Device ID	-
Product ID	-
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
## Operating System
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎23/‎2022
OS build	22621.963
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```
# Overview
A RecursionError occurs when I try to load the settings of my board.
In the KiCad Python Scripting Console, I use the `sys.getrecursionlimit()` function to print the recursion depth, which returns 1000.
I increase this limit to 2000 by using `sys.setrecursionlimit(2000)`, but KiCad crashes when it tries to load the settings...
# Log
```
Traceback (most recent call last):
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\controller\controller.py", line 40, in OnLoadClick
    self.model.get_track_length()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\model\model.py", line 142, in get_track_length
    info = track_data.find_min_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\lengthtrack.py", line 68, in find_min_track
    return findtrack.get_min_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 396, in get_min_track
    self.find_next_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 301, in find_next_track
    self.find_next_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 301, in find_next_track
    self.find_next_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 301, in find_next_track
    self.find_next_track()
  [Previous line repeated 988 more times]
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 299, in find_next_track
    self.check_track()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 272, in check_track
    self.find_hole_pad()
  File "C:\Users\<username>\Documents\KiCad\6.0\3rdparty\plugins\vn_onekiwi_length-matching\onekiwi\kicad\findtrack.py", line 251, in find_hole_pad
    if pad.GetPosition() == current_point:
  File "C:\Program Files\KiCad\6.0\bin\Lib\site-packages\pcbnew.py", line 661, in __eq__
    def __eq__(self,other):            return (self.x==other.x and self.y==other.y)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by thanhduongvs** [comment]
@olivierov Thanks for the report. Please wait for the updates
